name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # Change if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu               # Change if needed
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/"
          target: "/var/www/react-app/build"

      - name: Restart nginx on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu               # Change if needed
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo systemctl restart nginx
